import uuid

from sqlalchemy import Uuid, text
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPkMixin:
    """Primary key generated by Postgres core (gen_random_uuid(), PG13+), not the app."""

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )


class TenantScopedMixin:
    """tenant_id column only — no FK here.

    Direct children of tenant declare a plain FK to tenant(id) themselves;
    children of another tenant-scoped table declare a composite FK to
    parent(id, tenant_id) instead, so a row can never claim the right
    tenant_id while pointing at a different tenant's parent row. Which one
    applies differs per model, so it's left to each model's __table_args__
    rather than baked into this mixin.
    """

    tenant_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), nullable=False, index=True)
